apiVersion: 1

deleteDatasources:
  - name: Elastic
    orgId: 1

datasources:
  - name: Elastic
    type: elasticsearch
    orgId: 1
    access: proxy
    database: "[video-metrics-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70
    editable: true
