version: '3.8'

networks:
  flink-net:
    external: true

volumes:
  flink-checkpoints-directory:

services:
  jobmanager:
    image: flink:1.11.0-scala_2.11
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: "standalone-job"
    volumes:
      - ../build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
    networks:
      - flink-net

  taskmanager:
    image: flink:1.11.0-scala_2.11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    volumes:
      - ../build/libs:/opt/flink/usrlib
      - ../conf/flink:/opt/flink/conf
      - flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
    networks:
      - flink-net

